/* Generated by Yosys 0.9+4292 (git sha1 4a946ba9b, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "pattern_generator.sv:1.1-52.10" *)
module pattern_generator(i_clk, i_rst_n, i_force_step_value, i_force_step_trigger, i_step_trigger, i_step_polarity, i_step_reverse, i_brake, o_pattern);
  (* src = "pattern_generator.sv:35.2-51.5" *)
  wire [2:0] _00_;
  (* src = "pattern_generator.sv:0.0-0.0" *)
  wire [31:0] _01_;
  (* src = "pattern_generator.sv:29.33-29.40" *)
  wire [31:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "pattern_generator.sv:29.15-29.24" *)
  wire _07_;
  (* src = "pattern_generator.sv:30.15-30.24" *)
  wire _08_;
  wire [2:0] _09_;
  (* src = "pattern_generator.sv:0.0-0.0" *)
  wire [5:0] _10_;
  (* src = "pattern_generator.sv:30.33-30.40" *)
  wire [31:0] _11_;
  (* src = "pattern_generator.sv:29.14-29.41" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _12_;
  (* src = "pattern_generator.sv:30.14-30.41" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _13_;
  (* src = "pattern_generator.sv:45.14-45.49" *)
  wire [2:0] _14_;
  (* src = "pattern_generator.sv:47.19-47.59" *)
  wire [5:0] _15_;
  (* src = "pattern_generator.sv:9.21-9.28" *)
  input i_brake;
  (* src = "pattern_generator.sv:2.21-2.26" *)
  input i_clk;
  (* src = "pattern_generator.sv:5.21-5.41" *)
  input i_force_step_trigger;
  (* src = "pattern_generator.sv:4.21-4.39" *)
  input [2:0] i_force_step_value;
  (* src = "pattern_generator.sv:3.21-3.28" *)
  input i_rst_n;
  (* src = "pattern_generator.sv:7.21-7.36" *)
  input i_step_polarity;
  (* src = "pattern_generator.sv:8.21-8.35" *)
  input i_step_reverse;
  (* src = "pattern_generator.sv:6.21-6.35" *)
  input i_step_trigger;
  (* src = "pattern_generator.sv:10.21-10.30" *)
  output [5:0] o_pattern;
  reg [5:0] o_pattern;
  (* src = "pattern_generator.sv:22.14-22.18" *)
  reg [2:0] step;
  (* multirange = {0{1'b0}} *)
  (* src = "pattern_generator.sv:13.25-13.33" *)
  wire [35:0] step_lut;
  (* src = "pattern_generator.sv:24.14-24.21" *)
  wire [2:0] step_m1;
  (* src = "pattern_generator.sv:23.14-23.21" *)
  wire [2:0] step_p1;
  (* src = "pattern_generator.sv:25.14-25.22" *)
  wire [2:0] step_sel;
  assign _02_ = step + (* src = "pattern_generator.sv:29.33-29.40" *) 32'd1;
  assign _03_ = | { i_step_trigger, i_force_step_trigger };
  assign _05_ = ~ i_force_step_trigger;
  assign _06_ = ~ i_step_trigger;
  assign _04_ = & { _06_, _05_ };
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_generator.sv:35.2-51.5" *)
  always @(posedge i_clk, negedge i_rst_n)
    if (!i_rst_n) o_pattern <= 6'h00;
    else if (_04_) o_pattern <= _15_;
  (* \always_ff  = 32'd1 *)
  (* src = "pattern_generator.sv:35.2-51.5" *)
  always @(posedge i_clk, negedge i_rst_n)
    if (!i_rst_n) step <= 3'h0;
    else if (_03_) step <= _00_;
  assign _07_ = step == (* src = "pattern_generator.sv:29.15-29.24" *) 3'h5;
  assign _08_ = ! (* src = "pattern_generator.sv:30.15-30.24" *) step;
  assign _01_[31:1] = step_sel * (* src = "pattern_generator.sv:0.0-0.0" *) 31'h00000003;
  assign _09_ = i_step_trigger ? (* full_case = 32'd1 *) (* src = "pattern_generator.sv:44.8-44.22|pattern_generator.sv:44.5-48.8" *) _14_ : 3'hx;
  assign _00_ = i_force_step_trigger ? (* full_case = 32'd1 *) (* src = "pattern_generator.sv:40.8-40.28|pattern_generator.sv:40.4-49.7" *) i_force_step_value : _09_;
  wire [35:0] _35_ = 36'h86228c511;
  assign _10_ = _35_[$signed({ _01_[31:1], 1'h0 }) +: 6];
  assign _11_ = step - (* src = "pattern_generator.sv:30.33-30.40" *) 32'd1;
  assign { _12_[31:3], step_p1 } = _07_ ? (* src = "pattern_generator.sv:29.14-29.41" *) 32'd0 : _02_;
  assign { _13_[31:3], step_m1 } = _08_ ? (* src = "pattern_generator.sv:30.14-30.41" *) 32'd5 : _11_;
  assign step_sel = i_step_reverse ? (* src = "pattern_generator.sv:31.14-31.48" *) step_m1 : step_p1;
  assign _14_ = i_step_polarity ? (* src = "pattern_generator.sv:45.14-45.49" *) step_p1 : step_m1;
  assign _15_ = i_brake ? (* src = "pattern_generator.sv:47.19-47.59" *) 6'h07 : _10_;
  assign _01_[0] = 1'h0;
  assign _12_[2:0] = step_p1;
  assign _13_[2:0] = step_m1;
  assign step_lut = 36'h86228c511;
endmodule
